rvm:
  - "2.1.2"
env: 
  - "RAILS_ENV=test DB=mysql COVERALLS_SILENT=true"
install:
  - sudo apt-get -y install pwgen libicu-dev
  - bundle install
before_script:
  - cp config/database.travis.yml config/database.yml
  - mkdir -p public/uploads
  - bundle exec rake db:create db:migrate db:test:prepare
script:
  - bundle exec rake
