FROM ruby:2.3.1
MAINTAINER Franz Sommer <franz.sommer@wingolf.org>

RUN apt-get update -qq && apt-get install -y build-essential nodejs wget
RUN apt-get install -y libssl-dev g++ libxml2 libxslt-dev libreadline-dev libicu-dev imagemagick libmagick-dev libmagickwand-dev pwgen sendmail

RUN apt-get remove -y graphicsmagick-libmagick-dev-compat
RUN apt-get install -y libmagickwand-dev
RUN apt-get install -y libicu-dev

RUN mkdir /tmp/phantomjs && cd /tmp/phantomjs
RUN wget http://phantomjs.googlecode.com/files/phantomjs-1.8.1-linux-x86_64.tar.bz2
RUN tar xf phantomjs-1.8.1-linux-x86_64.tar.bz2
RUN cp ./phantomjs-*/bin/phantomjs /usr/bin/phantomjs
RUN rm -r /tmp/phantomjs

RUN mkdir /usr/src/app 

## Caching Using the box Volume
ENV BUNDLE_PATH /box 

# Copy the Gemfile and Gemfile.lock into the image. 
# Temporarily set the working directory to where they are. 
WORKDIR /tmp 
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install 