development:
  adapter: postgresql
  encoding: unicode
  database: wingolfsplattform_development
  pool: 25
  username: postgres
  password: secret
  host: postgres
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: wingolfsplattform_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: postgres
  password: secret
  host: postgres
  port: 5432
